/*CRIAÇÃO DA TABELA ANTES DE FAZER A FUNCTION */


CREATE TABLE PRODUTO
  (
    ID    NUMBER (3),
    NOME  VARCHAR (120) NOT NULL,
    PRECO NUMBER (10,2) NOT NULL,
    CONSTRAINT NOME_UNIQUE UNIQUE (NOME)
  );
SELECT * FROM PRODUTO;

-----------------------------------------------
/* CRIANDO A FUNÇÃO */

CREATE OR REPLACE
  FUNCTION FUNC_UPDPRODUTO(
      P_ID    IN PRODUTO.ID%TYPE,
      P_NOME  IN PRODUTO.NOME%TYPE,
      P_PRECO IN PRODUTO.PRECO%TYPE)
    RETURN NUMBER
  IS
    V_QTDE  NUMBER(1);
    P_SAIDA NUMBER(3);
    V_ID    NUMBER(6);
  BEGIN
    P_SAIDA         := 0;
    IF TRIM(P_NOME) IS NOT NULL AND LENGTH(TRIM(P_NOME)) <= 120 THEN /*TRIM TIRA OS ESPAÇOS ENTRE OS TEXTOS E LENGTH FAZ A VERIFICAÇÃO DO TANTO DE CARACTER EXISTENTE NO TEXTO */
      IF P_PRECO    >= 1000 AND P_PRECO <=5000 THEN
        SELECT COUNT(*) INTO V_QTDE FROM PRODUTO WHERE ID = P_ID;
        IF V_QTDE = 1 THEN
          SELECT COUNT(*)
          INTO V_QTDE
          FROM PRODUTO
          WHERE UPPER(TRIM(NOME)) = UPPER(TRIM(P_NOME))
          AND ID                 <> P_ID;
          IF V_QTDE               = 0 THEN
            UPDATE PRODUTO SET NOME = P_NOME, PRECO = P_PRECO WHERE ID = P_ID;
          ELSE
            P_SAIDA := -996; -- NOME JÁ EXISTE NA TABELA
          END IF;
        ELSE
          P_SAIDA := -997; -- PRODUTO NAO EXISTE PARA SER ALTERADO
        END IF;
      ELSE
        P_SAIDA := -998; -- PRECO FORA DA FAIXA
      END IF;
    ELSE
      P_SAIDA := -999; -- NOME NULO OU MAIOR QUE 120 CARACTERES
    END IF;
    COMMIT;
    RETURN P_SAIDA;
  END;

  -----------------------------------------
 /* VERIFICAÇÃO DAS INFORMAÇÕES INSERIDAS E RETORNO*/
  DECLARE
    RETORNO NUMBER(3);
  BEGIN
    RETORNO := FUNC_UPDPRODUTO(5, 'Martelo', 1000);
    DBMS_OUTPUT.PUT_LINE('CODIGO ERRO : ' || RETORNO);
    IF RETORNO = -999 THEN
      DBMS_OUTPUT.PUT_LINE('O NOME DEVE TER ATÉ 120 CARACTERES OU  NÃO DEVE SER NULO !!!, ESQUISITO');
    ELSIF RETORNO = -998 THEN
      DBMS_OUTPUT.PUT_LINE('O PREÇO DEVE ESTAR ENTRE 1000 E 5000!!!, ANIMAL');
    ELSIF RETORNO = -997 THEN
      DBMS_OUTPUT.PUT_LINE('NAO EXISTE O PRODUTO PESQUISADO PARA ALTERAR!!!');
    ELSIF RETORNO = -996 THEN
      DBMS_OUTPUT.PUT_LINE('O REGISTRO JÁ EXISTE !!!, BURRO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('REGISTRO ATUALIZADO COM SUCESSO!!! YES BABY');
    END IF;
  END;
  