DROP TABLE FUNCIONARIOS;

CREATE TABLE FUNCIONARIOS AS (SELECT * FROM EMPLOYEES);

CREATE TABLE LOG_FUNCIONARIOS (
    LOG_ID NUMBER (12) PRIMARY KEY,
    EMPLOYEE_ID NUMBER (6) NOT NULL,
    SALARY_ANTES NUMBER (8,2),
    SALARY_DEPOIS NUMBER (8,2),
    JOB_ID_ANTES NUMBER (10),
    JOB_ID_DEPOIS NUMBER (10),
    USUARIO VARCHAR2 (30) NOT NULL,
    DATA_HORA DATE NOT NULL,
    OPERACAO CHAT (1)   NOT NULL, --- I= INSERT, U = UPDATE , D = DELETE----

);

CREAT SEQUENCE SEQ_LOG_FUNCIONARIOS
NOCACHE 
NOCYCLE
MAXVALUE 999999999999;

