DECLARE
    X NUMBER (3);
    Y NUMBER (2);
    NOME_CODIGO VARCHAR2 (120) := 'BLOCO_PROGRAMAÇÃO';
    
BEGIN
    X := 10;
    Y := 8951.12;
    X:= X + 20;
   
    DBMS_OUTPUT.PUT_LINE ('OK');
EXCEPTION

    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE ('ERROOOOOOOOOOOOOOOOOO'); 
    DBMS_OUTPUT.PUT_LINE (SQLCODE); -- RETORNA O CODIGO DE ERRO
    DBMS_OUTPUT.PUT_LINE (SQLERRM); -- RETORNA A DESCRIÇÃO DO CODIGO DE ERRO
    DBMS_OUTPUT.PUT_LINE (DBMS_UTILITY.FORMAT_ERROR_BACKTRACE); -- MOSTRA O ERRO E A LINHA DO ERRO 
    DBMS_OUTPUT.PUT_LINE (USER); -- RETORNA O USUARIO 
    DBMS_OUTPUT.PUT_LINE (NOME_CODIGO); -- RETORNA O NOME DO MEU CODIGO DECLARADO NO DECLARE
END;