DECLARE 

    V_SALARY EMPLOYEES.SALARY%TYPE;

BEGIN
    SELECT SALARY INTO V_SALARY
        FROM EMPLOYEES WHERE EMPLOYEE_ID = 107;
        DBMS_OUTPUT.PUT_LINE ('SALARY',|| V_SALARY);


FOR RS IN (SELECT FIRST_NAME, SALARY,
                SALARY * 2 AS NOVO_SALARIO, EMAIL AS CORREIO
                FROM EMPLOYEES WHERE DEPARTMENT_ID = 60)

LOOP
    DBMS_OUTPUT.PUT_LINE ('__________________________');
    DBMS_OUTPUT.PUT_LINE ('NOME=' || RS.FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE ('SALARIO =' || RS.SALARY);
    DBMS_OUTPUT.PUT_LINE ('NOVO SALARIO=' || RS.NOVO_SALARIO);
    DBMS_OUTPUT.PUT_LINE ('EMAIL=' || RS.CORREIO);
    DBMS_OUTPUT.PUT_LINE ('__________________________');

END LOOP;

END;

SELECT FIRST_NAME , SALARY, EMAIL FROM EMPLOYEES WHERE DEPARTMENT_ID = 60